services:
  - type: web
    name: game-recommender-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn 'recommender:GameRecommender().app'
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
    runtime: python3